version: 0.2
env:
  parameter-store:
    DOCKERHUB_USER: "dockerhub-user"
    DOCKERHUB_PASS: "dockerhub-pass"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 245395156258.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t lego-assistant-app .
      - docker tag lego-assistant-app:latest 245395156258.dkr.ecr.eu-central-1.amazonaws.com/lego-assistant-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 245395156258.dkr.ecr.eu-central-1.amazonaws.com/lego-assistant-app:latest

artifacts:
  files:
    - Dockerrun.aws.json